DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  username VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  age INT NOT NULL
);
insert into EMPLOYEE(NAME, EMAIL, USERNAME, AGE) values('Employee', 'sgsakthi1992@gmail.com', 'employee', 25);
